### ISSUE TITLE
Getting error : SPLoaderError.loadComponentError

### ISSUE THREAD

**Issue by prasantabhowmik** [CloudDesignBox/cdb-promoted-links#6]
Hi, 

I am getting the below error when trying to add the app to an modern page o365.

I have checked all the urls are correct.

TECHNICAL DETAILS
[SPLoaderError.loadComponentError]:
***Failed to load component "5b0eac5a-50ba-4e01-8eb4-1767151d07f8" (CloudDesignBoxPromotedLinksWebPart).
Original error: ***Failed to load URL '/SiteAssets/CDBPromotedLinks/cdbpromotedlinks-clouddesignboxpromotedlinkswebpartstrings_en-us_765458216e451186e10982218c7e2d58.js' for resource 'CloudDesignBoxPromotedLinksWebPartStrings' in component '5b0eac5a-50ba-4e01-8eb4-1767151d07f8' (CloudDesignBoxPromotedLinksWebPart). There was a network problem.

***INNERERROR:
***Failed to load URL '/SiteAssets/CDBPromotedLinks/cdbpromotedlinks-clouddesignboxpromotedlinkswebpartstrings_en-us_765458216e451186e10982218c7e2d58.js' for resource 'CloudDesignBoxPromotedLinksWebPartStrings' in component '5b0eac5a-50ba-4e01-8eb4-1767151d07f8' (CloudDesignBoxPromotedLinksWebPart). There was a network problem.
***CALLSTACK:
Error
    at t [as constructor] (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-07-27.006/sp-pages-assembly_en-us_29e72c693acaac6528936578683809e9.js:662:16003)
    at new t (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-07-27.006/sp-pages-assembly_en-us_29e72c693acaac6528936578683809e9.js:1549:20443)
    at Function.e.buildErrorWithVerboseLog (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-07-27.006/sp-pages-assembly_en-us_29e72c693acaac6528936578683809e9.js:1549:15140)
    at Function.e.buildLoadComponentError (https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-07-27.006/sp-pages-assembly_en-us_29e72c693acaac6528936578683809e9.js:1549:11339)
    at https://spoprod-a.akamaihd.net/files/sp-client-prod_2018-07-27.006/sp-pages-assembly_en-us_29e72c693acaac6528936578683809e9.js:1549:67232

Thanks,
Pras

**Comment by prasantabhowmik** [comment]
I think I have found the solution in old from the old Issue.

**Comment by terriyaki0212** [comment]
How did you resolve this error? I'm getting the exact error message as well.

**Comment by CloudDesignBox** [comment]
Please see this thread: https://github.com/CloudDesignBox/cdb-promoted-links/issues/1
